#security:
#
#    firewalls:
#        # order matters! This must be before the ^/ firewall
#        login_firewall:
#            pattern:   ^/login$
#            anonymous: ~
#        secured_area:
#            pattern:    ^/
#            form_login: ~
#
#    access_control:
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/, roles: ROLE_ADMIN }