security:
     role_hierarchy:
         ROLE_ADMIN:       ROLE_USER
         ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

     providers:
         main:
             entity: { class: MailerBundle\Entity\User }

     firewalls:
         dev:
             pattern:  ^/(_(profiler|wdt)|css|images|js)/
             security: false

         default:
             pattern: ^/
             anonymous: ~
             form_login:
                 check_path: login
                 login_path: login
             logout:
                 path:   logout
                 target: site

     access_control:
         - { path: ^/$,      roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/email$, roles: ROLE_USER }