site:
    path: /
    defaults: { _controller: MailerBundle:Site:index }

email:
    path: /email
    defaults: { _controller: emailnotifier:indexAction }

send_email:
    path: /email/send
    defaults: { _controller: emailnotifier:sendAction }

login:
    path: /login
    defaults: { _controller: MailerBundle:Site:login }

signup:
    path: /signup
    defaults: { _controller: MailerBundle:Site:signup }