site:
    path: /
    defaults: { _controller: MailerBundle:Site:index }

email:
    path: /email
    defaults: { _controller: mailer.emailnotifier:indexAction }

send_email:
    path: /email/send
    defaults: { _controller: mailer.emailnotifier:sendAction }

login:
    path: /login
    defaults: { _controller: MailerBundle:Site:login }